use_frameworks!

target 'PodDemo1_Example' do
  pod 'PodDemo1', :path => '../'

  target 'PodDemo1_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
